### ISSUE TITLE
Crash from playing with friends after 1 or 2 fights

### ISSUE THREAD

**Issue by ZachEagan** [Tempus/Slay-the-Spire-Together#12] opened 2021-03-13 21:31 UTC
[sendToDevs.zip](https://github.com/Tempus/Slay-the-Spire-Together/files/6135617/sendToDevs.zip)
 
Logs above. Really cool mod!

**Comment by Tempus** [comment] 2021-03-13 21:58
Duplicate of #10, the second one today! Closing. Thanks for the report.

**Closed by Tempus** 2021-03-13 21:58 UTC
