### ISSUE TITLE
Crashes - Null Pointer exception in CardCrawlGame Render

### ISSUE THREAD

**Issue by IDMUSIC** [Tempus/Slay-the-Spire-Together#11] opened 2021-03-13 20:57 UTC
Ran into this bug when looking at card rewards after a hallway fight and selecting a new room. 

Logs attached:
[SlayTheSpire.log](https://github.com/Tempus/Slay-the-Spire-Together/files/6135568/SlayTheSpire.log)
[SlayTheSpire_202103132047_1.log](https://github.com/Tempus/Slay-the-Spire-Together/files/6135570/SlayTheSpire_202103132047_1.log)

Thanks for the mod and hard work!

**Comment by Tempus** [comment] 2021-03-13 21:56
Duplicate of #10 oddly enough! Closing. Thanks for the report.

**Closed by Tempus** 2021-03-13 21:56 UTC
