### ISSUE TITLE
Co-op game crashed randomly

### ISSUE THREAD

**Issue by Arclen** [Tempus/Slay-the-Spire-Together#10] opened 2021-03-13 20:56 UTC
20:40:20.653 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at chronoMods.coop.CoopEmptyRoom$LockedRoomField$locked_467_Accessor.set(CoopEmptyRoom$LockedRoomField$locked_467_Accessor.java) ~[?:?]
	at chronoMods.steam.NetworkHelper.parseData(NetworkHelper.java:447) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.steam.NetworkHelper.update(NetworkHelper.java:101) ~[Spire%20with%20Friends.jar:?]
	at chronoMods.steam.NetworkHelper$SteamUpdate.Postfix(NetworkHelper.java:81) ~[Spire%20with%20Friends.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:900) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
20:40:20.668 INFO core.CardCrawlGame> PAUSE()
20:40:20.670 INFO core.CardCrawlGame> Game shutting down...
20:40:20.670 INFO core.CardCrawlGame> Flushing saves to disk...
20:40:20.671 INFO helpers.FileSaver> Save thread interrupted!
20:40:20.671 INFO core.CardCrawlGame> Shutting down publisher integrations...
20:40:20.674 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.

**Comment by Tempus** [comment] 2021-03-13 22:02
Received three reports of this today, two were caused by seed desyncs, one unknown cause. Seed desyncs typically occur with different versions of Spire with Friends, or running with different mods set up that will modify the game contents and not just the UI.

Solution will be multi-fold, better indication of mod mismatching, better indication of version mismatching, better resiliency to crashing in face of desyncs, and improved detection of room locking. Will implement for next update.

**Comment by Tempus** [comment] 2021-04-16 00:18
Fixed in 1.5

**Closed by Tempus** 2021-04-16 00:18 UTC
